spring:
    application:
        name: ace-monitor

server:
    port: 8764 #启动端口

security:
    user:
        name: whb
        password: 123456
        role: USER
eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/